# Official Release Pipeline

name: Build, Validate and Release

jobs:
- job: Build, Validate and Release
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 6.x