name: Build and Validate

on: 
  workflow_call:
    
jobs:
  build-and-validate:
    name: Build and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal